### ISSUE TITLE
Maximum setlocal recursion level reached after script running for some time.

### ISSUE THREAD

**Issue by Spacemax** [C0nw0nk/SteamCMD-AutoUpdate-Any-Gameserver#1]
See link for details http://stackoverflow.com/questions/11916823/batch-limitation-maximum-recursion-while-browsing-menus

**Comment by Spacemax** [comment]
Fix for this seems to be to move "setlocal enableDelayedExpansion" to top of batch and outside of loop. That way it doesn't get set repeatedly and cause the maximum recursion error.

**Comment by C0nw0nk** [comment]
Sorry for the late reply i have done so now.
