### ISSUE TITLE
AutoUpdate failing to detect Steam patch

### ISSUE THREAD

**Issue by Spacemax** [C0nw0nk/SteamCMD-AutoUpdate-Any-Gameserver#2]
Game is ARK: Survival Evolved. GameID 346110 is the client and 376030 is the Dedicated Server.

Only 346110 can populate a version check, it seems the devs haven't filled anything in for the Dedicated server on 376030.

Is there another method that can be used?
What field of the data changes when a new patch is applied?

**Comment by C0nw0nk** [comment]
I would suggest just using the primary game id. You have to understand its
called a DEV API for a reason because its still under development so you
can expect for allot of games to not yet have any values or data on their
API to be read.

http://store.steampowered.com/app/346110/

**Comment by Spacemax** [comment]
Thanks, I found a better way to do it. Example code here:

%steamcmd_path% +login anonymous +app_info_update 1 "346110" +app_info_print "346110" +quit >%~n0-latest-version.txt

This has much more reliable build info and seems to work well. 

The only thing left now is the Maximum setlocal recursion level reached - setlocal error that appears after a while.

Is there a way we can tunnel the command instead or endlocal it at some point?
